### Question
What will `catch exit(err)` return?


### Answer
`{'EXIT', err}`


